CREATE TABLE IF NOT EXISTS player_pool (
  id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  pool_key VARCHAR(128) NOT NULL UNIQUE,
  source_type ENUM('CPU_SEED', 'PACK_TEMPLATE') NOT NULL DEFAULT 'PACK_TEMPLATE',
  name VARCHAR(96) NOT NULL,
  age TINYINT UNSIGNED NOT NULL,
  position ENUM('GK', 'DEF', 'MID', 'ATT') NOT NULL,
  rarity ENUM('COMMON', 'RARE', 'EPIC', 'LEGENDARY') NOT NULL,
  overall_rating DECIMAL(5,2) NOT NULL,
  pace TINYINT UNSIGNED NOT NULL,
  shooting TINYINT UNSIGNED NOT NULL,
  passing TINYINT UNSIGNED NOT NULL,
  dribbling TINYINT UNSIGNED NOT NULL,
  defending TINYINT UNSIGNED NOT NULL,
  strength TINYINT UNSIGNED NOT NULL,
  goalkeeping TINYINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_player_pool_position_rarity (position, rarity, overall_rating DESC)
);
