UPDATE league_tiers
SET
  team_count = 20,
  sort_order = CASE code
    WHEN 'BEGINNER_I' THEN 1
    WHEN 'BEGINNER_II' THEN 2
    WHEN 'BEGINNER_III' THEN 3
    WHEN 'BRONZE_I' THEN 4
    WHEN 'BRONZE_II' THEN 5
    WHEN 'BRONZE_III' THEN 6
    WHEN 'SILVER_I' THEN 7
    WHEN 'SILVER_II' THEN 8
    WHEN 'SILVER_III' THEN 9
    WHEN 'GOLD_I' THEN 10
    WHEN 'GOLD_II' THEN 11
    WHEN 'GOLD_III' THEN 12
    WHEN 'PLATINUM_I' THEN 13
    WHEN 'PLATINUM_II' THEN 14
    WHEN 'PLATINUM_III' THEN 15
    WHEN 'LEGENDS' THEN 16
    ELSE sort_order
  END,
  is_legends = (code = 'LEGENDS'),
  promotion_threshold_points = CASE code
    WHEN 'BEGINNER_I' THEN 25
    WHEN 'BEGINNER_II' THEN 50
    WHEN 'BEGINNER_III' THEN 75
    WHEN 'BRONZE_I' THEN 125
    WHEN 'BRONZE_II' THEN 175
    WHEN 'BRONZE_III' THEN 225
    WHEN 'SILVER_I' THEN 300
    WHEN 'SILVER_II' THEN 375
    WHEN 'SILVER_III' THEN 450
    WHEN 'GOLD_I' THEN 550
    WHEN 'GOLD_II' THEN 650
    WHEN 'GOLD_III' THEN 750
    WHEN 'PLATINUM_I' THEN 1000
    WHEN 'PLATINUM_II' THEN 1500
    WHEN 'PLATINUM_III' THEN 2000
    WHEN 'LEGENDS' THEN NULL
    ELSE promotion_threshold_points
  END
WHERE code IN (
  'BEGINNER_I',
  'BEGINNER_II',
  'BEGINNER_III',
  'BRONZE_I',
  'BRONZE_II',
  'BRONZE_III',
  'SILVER_I',
  'SILVER_II',
  'SILVER_III',
  'GOLD_I',
  'GOLD_II',
  'GOLD_III',
  'PLATINUM_I',
  'PLATINUM_II',
  'PLATINUM_III',
  'LEGENDS'
);
