// Auto-generated by scripts/generate-build-meta.mjs
export const APP_VERSION = "0.0.72" as const;
export const APP_VERSION_LABEL = "v0.0.72" as const;
export const APP_BUILD_TIMESTAMP = "1773341843727" as const;
export const APP_CACHE_BUST = "0-0-72-1773341843727" as const;
