// Auto-generated by scripts/generate-build-meta.mjs
export const APP_VERSION = "0.0.69" as const;
export const APP_VERSION_LABEL = "v0.0.69" as const;
export const APP_BUILD_TIMESTAMP = "1773318440917" as const;
export const APP_CACHE_BUST = "0-0-69-1773318440917" as const;
