// Auto-generated by scripts/generate-build-meta.mjs
export const APP_VERSION = "1.0.1" as const;
export const APP_VERSION_LABEL = "v1.0.1" as const;
export const APP_BUILD_TIMESTAMP = "1773057587339" as const;
export const APP_CACHE_BUST = "1-0-1-1773057587339" as const;
